cardsite/urls.py
from django.urls import path, include
from .views import (
    ItemDetailView, 
    CheckoutView, HomeView, 
    add_to_cart, 
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    order_summary_view,
    ApplyCoupon,
    send_mail_of_last_order,
    show_code,\
    AddCard,
    googleplay,
    amazon,
    netflix,
    )

app_name = 'cardsite'

urlpatterns = [
    path('', HomeView.as_view(), name='item-list'),
    path('product/<slug>/', ItemDetailView.as_view() , name='product'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('apply-coupon', ApplyCoupon.as_view(), name='apply-coupon'),
    path('mycode', show_code , name='mycode'),
    path('add-card', AddCard.as_view() , name='add-card'),
    path('googleplay', googleplay, name='googleplay'),
    path('amazon', amazon, name='amazon'),
    path('netflix', netflix, name='netflix'),
    path('order-summary', order_summary_view.as_view(), name='order-summary'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('sendamail', send_mail_of_last_order, name='sendamail'),
]

encoder/urls.py
from django.urls import path, include
from .views import (
    encoder
    )

app_name = 'encoder'

urlpatterns = [
    path('', encoder, name='encoder'),
    
]

giftcardsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('cardsite.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('encode', include('encoder.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cardsite/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse


class Card(models.Model):
    active = models.BooleanField(default=True)
    code = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class UsedCard(models.Model):
    active = models.BooleanField(default=False)
    code = models.CharField(max_length=30)
    description = models.TextField()
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


CATAGORY_CHOICES = (
    ('GP', 'Google Play'),
    ('AM', 'AMAZON'),
    ('NF', 'NETFLIX'),
    ('IT', 'ITUNES'),
    ('ST', 'STEAM')
)



class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    catagory = models.CharField(choices=CATAGORY_CHOICES, max_length=2)
    iscode = models.BooleanField(default=True)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to='pics')
    gift_cards = models.ManyToManyField(Card, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('cardsite:product', kwargs={
            'slug': self.slug
        })
    def get_add_to_cart_url(self):
        return reverse('cardsite:add-to-cart', kwargs={
            'slug': self.slug
        })
    def get_remove_from_cart_url(self):
        return reverse('cardsite:remove-from-cart', kwargs={
            'slug': self.slug
        })


    def getAvail(self):
        return self.gift_cards.all().count()


    def isAvail(self):
        if self.gift_cards.all():
            return True
        else:
            return False


    def get_label_text(self):
        if self.isAvail():
            return 'In stock'
        else:
            return 'Sold out'
    

    def get_label_color(self):
        if self.isAvail():
            return 'primary'
        else:
            return 'danger'

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"


    def get_total_item_price(self):
        return self.item.price * self.quantity

    def get_total_discount_item_price(self):
        return self.item.discount_price * self.quantity

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()



class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add = True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    final_cards = models.ManyToManyField(UsedCard, blank=True)

    def __str__(self):
        return self.user.username


    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total = total + order_item.get_final_price()
        if self.coupon:
            if self.coupon.lessen == 0:
                total -= ((self.coupon.percent * total)/100)
            else:
                total -= self.coupon.lessen
        return float(int(total))
    

    def get_discount(self):
        total = 0
        ret = 0
        for order_item in self.items.all():
            total = total + order_item.get_final_price()
        if self.coupon:
            if self.coupon.lessen == 0:
                ret = ((self.coupon.percent * total)/100)
            else:
                ret = self.coupon.lessen

        return ret
    

    def get_order_no(self):
        return str(self.id)[::-1] + self.user.username[::-1].upper()


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=11, default=None)


    def __str__(self):
        return self.user.username



class Payment(models.Model):
    phone = models.CharField(max_length=11)
    trxid = models.CharField(max_length=20)
    amount = models.IntegerField(default=0)





class Coupon(models.Model):
    code = models.CharField(max_length=15)
    percent = models.IntegerField()
    lessen = models.IntegerField()
    date_from = models.DateTimeField()
    date_to = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    used_by = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    oneuse = models.BooleanField(default=True)

    def __str__(self):
        return self.code

templates/add-card.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}



<main>
  <div class="container wow fadeIn">

    <form action="{% url 'cardsite:add-card' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" name="submit" id="submit">
    </form>

  </div>
</main>

{% endblock content %}

templates/base.html
{% load static %}
{% load cart_template_tag %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block head_title %}{% endblock %}</title>
        {% block extra_head %}
        {% endblock %}
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
        <!-- Your custom styles (optional) -->
        <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    </head>
    <body>
  <div class='container-my' style="position:relative; min-height: 100vh;"> 
    <div class='content-wrap' style="padding-bottom: ;">
          <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">
    
          <!-- Brand -->
          <a class="navbar-brand waves-effect" href="/">
            <strong class="blue-text">GiftCardCodes</strong>
          </a>
    
          <!-- Collapse -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
            <!-- Left -->
            <ul class="navbar-nav mr-auto">
               
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link waves-effect btn btn-outline-secondary" href="{% url 'cardsite:mycode' %}" >Order Hostory</a>
              </li>
              {% endif %}
              
            </ul>
    
            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{%url 'cardsite:order-summary' %}" class="nav-link waves-effect">
                  <span class="badge red z-depth-1 mr-1"> {{request.user|cart_item_count}} </span>
                  <i class="fas fa-shopping-cart"></i>
                  <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link border border-light rounded waves-effect mr-1" href="{%url 'account_logout'%}">
                  Logout
                </a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link border border-light rounded waves-effect mr-1" href="{%url 'account_login'%}">
                  Login
                </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link border border-light rounded waves-effect mr-1" href="{%url 'account_signup'%}">
                    Signup
                  </a>
                </li>
              {% endif %}

            </ul>
    
          </div>
    
        </div>
      </nav>
      <!-- Navbar -->
      <div class="mt-5 pt-4">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
      </div>



        {% block content %}
        {% endblock content%}

        {% block extra_body %}
        {% endblock %}
</div>
        <!--Footer-->
  
  <footer class="page-footer text-center font-small col-12 position-absolute fadeIn" style="height:3.5rem">

    

    <!-- <hr class="my-4"> -->

    <!-- Social icons -->
    <!-- <div class="pb-4">
      <a href="https://www.facebook.com/shafinohin" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/shafinohin" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/channel/UCIDSjI-vFcKr-RLyyj061tg" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      
    </div> -->
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
      &nbsp; &nbsp; &nbsp;
      <a href="https://www.facebook.com/shafinohin" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/shafinohin" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/channel/UCIDSjI-vFcKr-RLyyj061tg" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->
</div>


  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
    </body>
</html>

templates/checkout.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}


<main>
  <div class="container wow fadeIn">

    <h2 class="my-5 h2 text-center">Checkout form</h2>

    <div class="row">

      <div class="col-md-8 mb-4">

        <div class="card">


          <!-- <form>
            {{form|crispy}}
          </form> -->
          
          <form method="POST" class="card-body">

            {% csrf_token %}
            <!--address-->
            <div class="md-form mb-5">

              {{form.email}}
              <p class="font-small font-weight-lighter">*leave blank for using default email address</p>
              <label for="{{form.email.auto_id}}" class="">Email</label>
            </div>


            <!--address-2-->
            <div class="md-form mb-5">
              
              {{form.phone}}
              <p class="font-small font-weight-lighter">*We will contact you by this number in case of system failure</p>
              <label for="{{form.phone.auto_id}}" class="">Phone Number (important)</label>
      
            </div>

            

            <hr>

            
            <div class="custom-control custom-checkbox">
              <input {% if form.save_info.value %} checked {% endif %} type="checkbox" class="custom-control-input"
                id="save-info" name="save_info">
              <label class="custom-control-label" for="save-info">Save this information for next time</label>
            </div>

            <hr>

            <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
                <input id="{{name}}" value="{{value}}" name="payment_option" type="radio" class="custom-control-input"
                  checked required>
                <label class="custom-control-label" for="{{name}}">{{name}}</label>
              </div>
              {% endfor %}

            </div>


            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

          </form>

        </div>

      </div>




      {% include "promo_snippet.html" %}
      {% block promo_block %}
      {% endblock %}

    </div>

  </div>
</main>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block head_title %}
Home
{% endblock %}

{% block content %}

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>




  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cardsite:googleplay' %}">Google Play</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cardsite:amazon' %}">Amazon</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cardsite:netflix' %}">Netflix</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        
        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt=""> -->
                  <img src="{{item.image.url}}" class="card-img-top">
                <a href="{{item.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                {% if item.iscode == False %}
                <a href="" class="grey-text">
                  <h5>{{item.get_catagory_display}}</h5>
                </a>
                {% endif %}
                <h5>
                  <strong>
                    <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{item.title}}
                      <span class="badge badge-pill {{item.get_label_color}}-color">{{item.get_label_text}}</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>৳  
                    {% if item.discount_price %}
                    {{item.discount_price}}
                    {% else %}
                    {{item.price}}
                    {% endif %}
                  </strong>
                </h4>
                {% if item.isAvail %}
                <a href="{{item.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </a>
                {% endif %}

              </div>
              <!--Card content-->

            </div>
            <!--Card-->
          

          </div>
          {% endfor %}


        </div>
        
        <!--Grid row-->

        

      </section>
      <!--Section: Products v.3-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn" style="padding-bottom: 50px;">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
         
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>
  <!--Main layout-->


{% endblock content %}

templates/item_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Here is the list of Items</h1>
{% for item in items %}
    {{item}}
{% endfor %}
{% endblock content%}

templates/order-summary.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    html,
    body,
    header,
    .carousel {
        height: 60vh;
    }

    @media (max-width: 740px) {

        html,
        body,
        header,
        .carousel {
            height: 100vh;
        }
    }

    @media (min-width: 800px) and (max-width: 850px) {

        html,
        body,
        header,
        .carousel {
            height: 100vh;
        }
    }
</style>




<!--Main layout-->
<main>
    <div class="container">


        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item Title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{forloop.counter }}</th>
                        <td>{{order_item.item.title}}</td>
                        <td>{{order_item.item.price}}</td>
                        <td>
                            <a href="{%url 'cardsite:remove-single-item-from-cart' order_item.item.slug %}"><i
                                    class="fas fa-minus mr-2"></i></a>
                            {{order_item.quantity}}
                            <a href="{%url 'cardsite:add-to-cart' order_item.item.slug %}"><i
                                    class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                            ৳{{order_item.get_total_discount_item_price}}
                            <span class="badge badge-success"> Saving ৳{{order_item.get_amount_saved}} </span>
                            {% else %}
                            ৳{{order_item.get_total_item_price}}
                            {% endif %}
                            <a href="{%url 'cardsite:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash-alt float-right"></i>
                            </a>
                        </td>

                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-primary float-right ' href="/">Continue Shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total:</b></td>
                        <td><b>৳{{object.get_total}}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-warning float-right ml-3' href="/checkout/">Proceed to Checkout</a>
                            <a class='btn btn-primary float-right ' href="/">Continue Shopping</a>

                        </td>
                    </tr>
                    {% endif %}

                </tbody>
            </table>

        </div>


    </div>
</main>
<!--Main layout-->


{% endblock content %}

templates/product.html
{% extends 'base.html' %}

{% block content %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-3 col-xl-4 col-lg-3 mb-4">

          <img src="{{object.image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_catagory_display}}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>৳{{object.price}}</del>
              </span>
              {% endif %}
              {% if object.discount_price %}
              <span>৳{{object.discount_price}}</span>
              {% else %}
              <span>৳{{object.price}}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>
            <!--
            <form class="d-flex justify-content-left">
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> 
            -->
            {% if object.isAvail %}
            <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            {% endif %}
            <a href="{{object.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p" type="submit">Remove from cart
              
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/promo_snippet.html
<div class="col-md-4 mb-4">

    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted">Your cart</span>
      <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
      {% for order_item in order_items %}
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0"> {{order_item.quantity}} x {{order_item.item.title}}</h6>
          <small class="text-muted">{{order_item.item.description}}</small>
        </div>
        <span class="text-muted">৳{{order_item.get_final_price}}</span>
      </li>
      {% endfor %}
      {% if order.coupon %}
      <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
          <h6 class="my-0">Promo code</h6>
          <small>{{order.coupon.code}}</small>
        </div>
        <span class="text-success">-৳{{order.get_discount}}</span>
      </li>
      {% endif %}
      <li class="list-group-item d-flex justify-content-between">
        <span>Total (BDT)</span>
        <strong>৳{{order.get_total}}</strong>
      </li>
    </ul>
    <!-- Cart -->

    <!-- Promo code -->
    {% if showCoupon %}
    <form method="POST" class="card p-2" action="{% url 'cardsite:apply-coupon' %}">
      {% csrf_token %}
      <div class="input-group">
        <!-- <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username"
          aria-describedby="basic-addon2"> -->
          {{couponForm.code}}
        <div class="input-group-append">
          <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
        </div>
      </div>
    </form>
    {% endif %}
    <!-- Promo code -->

  </div>